apiVersion: v1
kind: Service
metadata:
  name: user-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: user
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
    
    - name: http
      port: 8000
      targetPort: 8000
    
